### ISSUE TITLE
No HOSE for hydrogens

### ISSUE THREAD

**Issue by vosegaard** [Ratsemaat/HOSE_code_generator#1]
Thanks for the hose code generator, which works like a charm for carbons, but it only seems to generate the minimum code "H-1;(//)/" for all hydrogens. How do I generate a hose code for hydrogens?

**Comment by stefhk3** [comment]
Looks like a bug. We are looking at it.

**Comment by Ratsemaat** [comment]
Thank for bringing the issue to the attention. We updated the HOSE code generator such that with rdkit's "implicit" hydrogens the generator would throw an exception and with "explicit" setting all hydrogens are included in the HOSE codes.

**Comment by vosegaard** [comment]
Thanks for fixing the bug so fast - I'm impressed :-)
